[project]
name = "bridget"
version = "1.0.0"
description = "Bot for the palera1n Discord server"
authors = [
    {name = "Nebula", email = "me@itsnebula.net"},
    {name = "June Park", email = "rjp2030@outlook.com"}
]
dependencies = [
    "py-cord",
    "mongoengine>=0.27.0",
]
requires-python = ">=3.10,<4.0"
license = {text = "BSD-3-Clause"}
readme = "README.md"

[project.urls]

[tool.pdm.build]
includes = []

[tool.pdm.scripts]
bot.cmd = "bridget.bridget:main"
bot.env_file = ".env"

[tool.pyright]
extraPaths = ["__pypackages__/3.11/lib/"]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
