blank_issues_enabled: false
contact_links:
  - name: Main Discord server
  - url: https://discord.gg/palera1n
  - about: Join the server in the "Bot Rewrite Discussion" thread in #general for bot-rewrite releated disscussion.
