name: Format python code
on:
    push:
      paths:
        - bridget/**
        - .github/workflows/autopep8.yml
    workflow_dispatch:

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'autopep8 actions'
          git config --global user.email 'rjp2030@outlook.com'
          git commit -am "Automated autopep8 fixes"
          git push
