name: Lint script

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint with autopep8
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: --style pep8 --recursive --global-config ".flake8" --in-place .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Lint with flake8